substitutions:
  _REGION: 'asia-northeast1'
  _CONTAINER: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/rag-chat-streamlit/${REPO_NAME}:${SHORT_SHA}'
  _SERVICE_NAME: 'ou-chatbot'
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
- name: 'ubuntu'
  script: |
    touch .env
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t ${_CONTAINER} .
    docker push ${_CONTAINER}
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE_NAME}
    - '--image=${_CONTAINER}'
    - '--region=${_REGION}'
    - --max-instances=1
    - --min-instances=0
    - --port=8501
    - --ingress=all
    - --allow-unauthenticated